spring.application.name=scrum-planning-be

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/scrum_planning
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.thy.scrum_planning_be=DEBUG

# Server
server.port=8080
